### ISSUE TITLE
Most recent models are not always deployed

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/openmapflow#100]
**Context**: The 3 most recent models are chosen for deployment using this line: https://github.com/nasaharvest/openmapflow/blob/e1b3bb96da4933e5ff033c1ed0039d9c243ed6c4/openmapflow/config.py#L84

**Issue**: The above line uses the file age to sort, however, the file age depends on the latest `dvc pull` rather than the actual model file age. Therefore the most recent models are not always deployed.

**Potential solution**: Find another indicator to sort by for deployment.

**Comment by gabrieltseng** [comment]
It may also be nice to be able to control how many models are deployed
