### ISSUE TITLE
Access blocked: DVC’s request is invalid

### ISSUE THREAD

**Issue by eoproject2022** [nasaharvest/openmapflow#114]
I tried running the following scripts :

# Pull in data already available
!dvc pull -q

After running the above scripts i got the following output

Go to the following link in your browser:
    https://accounts.google.com/o/oauth2/auth?client_id=710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&response_type=code&approval_prompt=force

Enter verification code: 

When I click the above link i got the following message:

Access blocked: DVC’s request is invalid

iamnrajkumar@gmail.com
You can’t sign in because DVC sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of DVC, see [error details](https://accounts.google.com/).
Error 400: invalid_request

Please assist

**Comment by ivanzvonkov** [comment]
Thanks for creating this issue @eoproject2022 
This seems to be tied to the Google Colab oauth upgrade. It looks like a fix: https://github.com/iterative/dvc/issues/7867 may be available in a newer version of dvc. However, this version is not possible to install because Google Colab has an older python version (3.7). I am actively investigating a fix.

**Comment by yonas-g** [comment]
I am stuck on this error as well

**Comment by ivanzvonkov** [comment]
Current options being investigated:
- Move dvc remote storage from Google Drive to a publicly readable Google Cloud Storage Bucket (this will hopefully get around the authentication issue but will require additional permissions for pushing the model to dvc)
- Change python version inside Colab to be able to install a newer version of dvc

**Comment by ivanzvonkov** [comment]
This will be fixed when is merged #117
