### ISSUE TITLE
Python3 and openmapflow setup on Windows

### ISSUE THREAD

**Issue by MsPixels** [nasaharvest/openmapflow#116]
I have python 3 installed but it cannot be recognized when I run the openmapflow create dataset function (python3 -c "from datasets import datasets; from openmapflow.labeled_dataset import create_datasets; create_datasets(datasets)". )

I am adding a screenshot of what pops up when I print python3. 

![image](https://user-images.githubusercontent.com/110104000/199333678-c0a2712d-685d-4a14-8fdd-681a7c64360d.png)

Thank you

**Comment by ivanzvonkov** [comment]
Addressed in version `0.2.2`
